source "http://rubygems.org"

gem "decko"
gem "card", require: false

gem "mysql2", '~> 0.5'
gem "thin"
gem "card-mod-defaults"


# BACKGROUND
# A background gem is needed to run tasks like sending notifications in a background
# process.
# See https://github.com/decko-commons/decko/tree/master/card-mod-delayed_job
# for additional configuration details.
# gem "card-mod-delayed_job", path: "~/dev/decko/gem/mod"


# MONKEYS
# You can also create your own mods. Mod developers (or "Monkeys") will want some
# additional gems to support development and testing.
gem "card-mod-monkey", group: :development
gem "decko-rspec", group: :test
# gem "decko-cucumber", group: :cucumber, path: "~/dev/decko/gem/support"
# gem "decko-cypress", group: :cypress, path: "~/dev/decko/gem/support"
# gem "decko-profile", group: :profile, path: "~/dev/decko/gem/support"
# gem "decko-spring", path: "~/dev/decko/gem/support"

path "~/card-mods" do
  gem "card-mod-bookmarks"
  gem "card-mod-csv_import"
  gem "card-mod-fulltext"
  gem "card-mod-logger"
  gem "card-mod-pdfjs"
  gem "card-mod-social"
  gem "card-mod-solid_cache"
end

# PLATYPUSES
# This mod is strongly recommended for platypuses – coders working on the decko core
gem "card-mod-platypus"


# The following allows simple (non-gem) mods to specify gems via a Gemfile.
# You may need to alter this code if you move such mods to an unconventional location.
Dir.glob("mod/**/Gemfile").each { |gemfile| instance_eval File.read(gemfile) }
