source "http://rubygems.org"

path "~/card-mods/.semaphore/decko" do
  gem "decko"
  gem "card", require: false
end

gem "mysql2", '~> 0.5'
gem "thin"

path "~/card-mods/.semaphore/decko/mod" do
  gem "card-mod-defaults"
  gem "card-mod-monkey"
  gem "card-mod-platypus"
end

gem "decko-rspec", group: :test, path: "~/card-mods/.semaphore/decko/support"
# gem "decko-cucumber", group: :cucumber, path: "~/dev/decko/gem/support"
# gem "decko-cypress", group: :cypress, path: "~/dev/decko/gem/support"
# gem "decko-profile", group: :profile, path: "~/dev/decko/gem/support"
# gem "decko-spring", path: "~/dev/decko/gem/support"

path "~/card-mods" do
  Dir.chdir "#{Dir.home}/card-mods" do
    Dir.glob("card-mod-*").each do |mod|
      gem mod
    end
  end
end
