source "http://rubygems.org"

path "~/card-mods/.semaphore/decko" do
  gem "decko"
  gem "card", require: false
end

gem "mysql2", '~> 0.5'
gem "thin"

path "~/card-mods/.semaphore/decko/mod" do
  gem "card-mod-defaults"
  gem "card-mod-monkey"
  gem "card-mod-platypus"
end

gem "decko-rspec", group: :test, path: "~/card-mods/.semaphore/decko/support"
# gem "decko-cucumber", group: :cucumber, path: "~/dev/decko/gem/support"
# gem "decko-cypress", group: :cypress, path: "~/dev/decko/gem/support"
# gem "decko-profile", group: :profile, path: "~/dev/decko/gem/support"
# gem "decko-spring", path: "~/dev/decko/gem/support"

path "~/card-mods" do
  gem "card-mod-alias"
  gem "card-mod-bookmarks"
  gem "card-mod-counts"
  gem "card-mod-csv_import"
  gem "card-mod-fulltext"
  gem "card-mod-google_analytics"
  gem "card-mod-graphql"
  gem "card-mod-logger"
  gem "card-mod-lookup"
  gem "card-mod-mirror"
  gem "card-mod-new_relic"
  gem "card-mod-pdfjs"
  gem "card-mod-prosemirror_editor"
  gem "card-mod-social"
  gem "card-mod-solid_cache"
  gem "card-mod-tabs"
  gem "card-mod-thumbnail"
end
